#!/bin/sh

# check for messagebus group or add one
getent group polkit || /usr/sbin/groupadd -g 83 polkit

# check for messagebus user or add one
getent passwd polkit || /usr/sbin/useradd -g polkit -u 83 -d /var/empty -s /bin/false -c "PolicyKit User" polkit

# lock the account
/usr/bin/passwd -l polkit
